; https://docs.platformio.org/en/latest/platforms/espressif32.html

[platformio]
; uncomment to build an example
; src_dir = ./examples/blink
; src_dir = ./examples/serial
src_dir = ./examples/ota
; src_dir = ./examples/low-energy-consumption
; src_dir = ./examples/esp-now-le

[env]
board_build.partitions = partitions.csv
build_flags =
    ; to use e.g. as part of the firmware name 
    '-DPIOENV="${PIOENV}"'
 
    ; coding_standards
    -Wno-unused-variable
    -Wno-unused-but-set-variable
    -Wunreachable-code

    ; debug level 5=VERBOSE https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level
    ;  -DCORE_DEBUG_LEVEL=5
extra_scripts = pre:extra_script.py
framework = arduino
lib_deps =
    ; place global libs here or under extra.lib_deps_external (see below)
monitor_speed = 115200
platform = espressif32
upload_speed = 921600
; uncomment and configure when you have multiple ESPs connected
; upload_port = /dev/tty.usbserial-...
; monitor_port = /dev/tty.usbserial-...

; CUSTOM options
; You need manually inject these options into a section
; using ${extra.<name_of_option>} (see below)
[extra]
; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html
build_flags_psram =
    -DBOARD_HAS_PSRAM=1
    -mfix-esp32-psram-cache-issue ; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html#esp32-rev-v1
lib_deps_builtin =
  SPI
  Wire
lib_deps_external =
    tzapu/WiFiManager @ ^2.0.17
    ; https://github.com/mcuw/EspGhOta
    ; extend libs for all platforms here

[esp32]
build_flags =
    -DLED_BUILTIN=13
    ${env.build_flags}
lib_deps =
    ${env.lib_deps}
    ${extra.lib_deps_builtin}
    ${extra.lib_deps_external}
    ; extend libs only for esp32 based modules here


; *********
; * ESP32 *
; *********

; pio board config: https://docs.platformio.org/en/latest/platforms/espressif32.html
[env:esp32dev]
extends = esp32
board = esp32dev
build_flags =
    ${esp32.build_flags}
lib_deps =
    ${esp32.lib_deps}
